packages:
  - "packages/*"
  - "examples/*"
  - docs

allowBuilds:
  esbuild: false
  spawn-sync: false

catalog:
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.2.6
  vite-plus: 0.2.6
  vitest: 4.1.10
  "@vitest/browser": 4.1.10
  "@vitest/browser-playwright": 4.1.10
  "@vitest/coverage-v8": 4.1.10

minimumReleaseAgeExclude:
  - "@solidjs/start@2.0.0-rc.2"

overrides:
  vite: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
