packages:
  - "packages/*"
  - "examples/*"
  - docs

catalog:
  typescript: ^6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@^0.1.19
  vite-plus: ^0.1.19
  vitest: npm:@voidzero-dev/vite-plus-test@latest

overrides:
  vite: "catalog:"
  vitest: "catalog:"
patchedDependencies:
  '@solidjs/start': patches/@solidjs__start.patch

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
