packages:
  - "packages/*"
  - "examples/*"
  - docs

allowBuilds:
  esbuild: false
  spawn-sync: false

catalog:
  typescript: ^6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@0.2.1
  vite-plus: 0.2.1

overrides:
  vite: "catalog:"
  "@solidjs/start>h3": "2.0.1-rc.20"

patchedDependencies:
  "@solidjs/start": patches/@solidjs__start.patch

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
