name: checks

on: [push, pull_request]

jobs:
  check-all:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      # to write test coverage report comment
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm test:coverage
      - run: pnpm run check
      - run: pnpm run format:check
      - name: 'Report Coverage'
        if: always() 
        uses:  davelosert/vitest-coverage-report-action@v2