name: checks

on: [push]

jobs:
  check-all:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      # to write test coverage report comment
      pull-requests: write

    steps:
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "24"
          cache: false
      - run: vp install
      - run: vp check
      - run: vp test run --coverage

      - name: "Report Coverage"
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
