name: Release Packages

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "24"
          cache: false

        # workaround for voidzero-dev/setup-vp@v1 not putting pnpm in PATH
      - run: vp install -g pnpm

      - run: "vp run preparePublish"

      - run: "pnpm publish -r --no-git-checks --tag latest"
