name: Release Packages

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "24"
          cache: false

      - run: "npm install -g npm@11.15.0"

      - run: "vp run preparePublish"

      - run: |
          for f in ./dist/*.tgz; do
            npm stage publish "$f" --tag latest
          done
