name: qa

on: [pull_request]

jobs:
  qa:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      # to write test coverage report comment
      pull-requests: write

    steps:
      - uses: actions/checkout@v6
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "24"
      - run: vp run ci

      - uses: davelosert/vitest-coverage-report-action@v2
        if: always()
